### ISSUE TITLE
Help enlist pertinent altcoins

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq-assets#107]
We have atm a running proposal about listing fee policy:
https://github.com/bisq-network/proposals/issues/35 (please comment and/or vote)

This listing fee policy proposal concerns mainly the visible weak end of Bisq's altcoin list.
In parallel, we can also have a look on the top of the altcoin list.

On https://coinmarketcap.com/coins/ one can see the Top 100 Coins by Market Capitalization

From this Top20 list :
#3 XRP #5 EOS #6 XLM Stellar #8 ADA Cardano
are **not listed** on Bisq.

Noticeable is #10 which is XMR Monero. The best traded altcoin on Bisq.

#11 TRX (Tron) #12 MIOTA (Iota) #14 NEO #15 XEM (Nem) #16 XTZ (Tezos) #18 VET (VeChain) #19 QTUM
are also **not listed** on Bisq

I'll not browse entirely this TOP100. I stop the browsing here.
But in the TOP20 best performing altcoins, atm Bisq has only 9 listed.

I imagine there may be technical reasons why some of those altcoins cannot be listed on Bisq, and maybe other reasons.

But, given what XMR Monero is able to do from time to time,
I wonder if we shouldn't do something to help enlist some of the above actually not liste altcoins ? And if yes, for which altcoins ?

Thoughts welcome.

**Comment by cbeams** [comment]
This is more of a proposal itself than something for the bisq-assets repository. Most people will not see this issue, as most people do not watch this repository.

In any case, I have no interest in seeing proactive enlistment / recruitment of popular assets / altcoins, based on CoinMarketCap metrics or any other factor.

Individuals contributors are free to do as they please, but I would push back on anything that feels like "Bisq" trying to do something like this in an an official way.

I'll hold off on going into a lot of detail as to why. I've said much of it already in https://github.com/bisq-network/proposals/issues/35#issuecomment-414032049.

Please consider closing this issue, @HarryMacfinned, as I don't think it'll get much attention here.

**Comment by aejontargaryen** [comment]
I like this guy. @HarryMacfinned  Weren't you the one who gathered up a list of like 100 altcoins for Manfred to list? I'm not really big on the top 20 thing, but the idea of searching out alts with a preference and adding the ones Bisq traders want to trade... is definitely a step up from the current model. The problem with most coins listed on Bisq is they never intended nor planned to trade from the start.  
DRGL did.
We came to play.

@HarryMacfinned  Post a DRGL address

**Comment by ghost** [comment]
I close this issue as suggested by @cbeams , because indeed this repo may not be the best place for discussing the topic.
This doesn't close atm the proposed idea. I'll probably resubmit it as a proposal, but after the other running proposal concerning assets https://github.com/bisq-network/proposals/issues/35 , is closed and we have clear decisions.
